name: CI

on:
  create:
    branches: [ "release/**" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c $BUILD_CONFIG --no-restore
        
      - name: Run tests
        run: dotnet test -c $BUILD_CONFIG --no-restore --no-build --verbosity normal
        
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push **\*.nupkg --skip-duplicate -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}
